apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
    
      listen 80;
      server_name bitrix.local;
    
      client_max_body_size 8M; # __POST_SIZE_VALUE__
    
      proxy_read_timeout 888; # __TIMEOUT_VALUE__
      proxy_send_timeout 888; # __TIMEOUT_VALUE__
      proxy_connect_timeout 8; # __TIMEOUT_VALUE__
    
      root /var/www/app/web;
      index index.php index.html index.htm;
    
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }
    
      location ~ \.php$ {
    
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    
        fastcgi_read_timeout 888; # __TIMEOUT_VALUE__
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  bitrix.cnf: |
    [mysqld]
    default-time-zone = '+03:00' # __TIME_ZONE_VALUE__
    innodb_strict_mode = OFF

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini
data:
  bitrix.ini: |
    
    zend_extension = opcache
    opcache.enable = 1
    opcache.enable_cli = 1
    opcache.revalidate_freq = 0
    
    max_input_vars = 10000
    
    upload_max_filesize = 8M ; __POST_SIZE_VALUE__
    post_max_size = 8M ; __POST_SIZE_VALUE__
    
    max_execution_time = 888 ; __TIMEOUT_VALUE__
    
    sendmail_path = "php -f /k8s/scripts/php_sendmail.php"
    
    date.timezone = "Europe/Moscow" ; __TIME_ZONE_VALUE__
    
    display_errors = Off

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: bWVvdzg4ODg4ODg4 #base64
  mysql-user-password: c2l0ZW1hbmFnZXI= #base64
