
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: app-pv
#  labels:
#    type: local
#spec:
#  storageClassName: standard
#  capacity:
#    storage: 8Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: /home/docker/app-pvc
#    type: DirectoryOrCreate
#  persistentVolumeReclaimPolicy: Retain
#
#---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: default
spec:
#  volumeName: app-pv
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteMany

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
